"""Alembic 迁移模板 — 幂等 schema 收敛

将此文件复制到 alembic/versions/ 目录，修改：
- revision / down_revision
- add_patches 和 drop_patches 字典内容

Revision ID: <auto-generated>
Revises: <current_head>
Create Date: <auto-generated>
"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

revision: str = '<auto>'
down_revision: Union[str, None] = '<current_head>'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(conn, table: str, column: str) -> bool:
    """information_schema 列存在性探测"""
    result = conn.execute(
        text(
            "SELECT COUNT(*) FROM information_schema.columns "
            "WHERE table_schema = DATABASE() "
            "AND table_name = :table AND column_name = :col"
        ),
        {"table": table, "col": column},
    )
    return (result.scalar() or 0) > 0


def _table_exists(conn, table: str) -> bool:
    """information_schema 表存在性探测"""
    result = conn.execute(
        text(
            "SELECT COUNT(*) FROM information_schema.tables "
            "WHERE table_schema = DATABASE() AND table_name = :table"
        ),
        {"table": table},
    )
    return (result.scalar() or 0) > 0


def upgrade() -> None:
    conn = op.get_bind()

    # ── ADD 列（幂等探测） ──
    add_patches: dict[str, list[tuple[str, str]]] = {
        # "table_name": [
        #     ("column_name", "ALTER TABLE table_name ADD COLUMN column_name TYPE ..."),
        # ],
    }
    for table_name, patches in add_patches.items():
        if not _table_exists(conn, table_name):
            continue
        for column_name, alter_sql in patches:
            if _column_exists(conn, table_name, column_name):
                continue
            conn.execute(text(alter_sql))

    # ── DROP 列（幂等探测） ──
    drop_patches: dict[str, list[str]] = {
        # "table_name": ["col1", "col2"],
    }
    for table_name, columns in drop_patches.items():
        if not _table_exists(conn, table_name):
            continue
        for col in columns:
            if _column_exists(conn, table_name, col):
                conn.execute(text(f"ALTER TABLE {table_name} DROP COLUMN {col}"))


def downgrade() -> None:
    """这些列由 ORM 模型定义 / create_all 管理，downgrade 不必要。"""
    pass